### PR TITLE
Load associations defined in the seeds

### PR DESCRIPTION
**Pull request by givanse**
It assumes the existence of the logging function found in https://github.com/lykmapipo/sails-hook-seed/pull/8, of course is not a dependency.

Usage example:

``` js
// Model
module.exports = {
    attributes: {
        name: {type: 'string'},
        users: {
          collection: 'user',
          via: 'groups',
          dominant: true
        } 
    }
};
```

``` js
//seed
{
    GroupSeed: {
        name: 'group one',
         users: [1]
    }
};
```

(the same as the one in the added test)

This patch avoids errors like this one:

``` js
error: [Error (E_UNKNOWN) Encountered an unexpected error] Details:  [ { type: 'insert',
    collection: 'group_users__user_groups',
    criteria: { user_groups: 999, group_users: 1 },
    values: { user_groups: 999, group_users: 1 },
    err: [Error: Associated Record For user with id = 999 No Longer Exists] } ]
```

That happens when a seed with an association is loaded before the associated record has been loaded.

### CODE REVIEW

**Comment by lykmapipo** [comment]
@givanse 

Am on it

**Comment by lykmapipo** [comment]
@givanse 

Can we discuss on this, so that we can implement a total feature on seeding relations

Regard

**Comment by givanse** [comment]
Sure, what are your concerns with the current patch? Or what else would you like to see?

**Comment by lykmapipo** [comment]
@givanse There are not problems with patch

Its about association seeding. See [issue](https://github.com/lykmapipo/sails-hook-seed/issues/9). sails offer three type of association [see Association](http://sailsjs.org/#!/documentation/concepts/ORM/Associations)
- [One-to-One](http://sailsjs.org/#!/documentation/concepts/ORM/Associations/OnetoOne.html)
- [One-to-Many](http://sailsjs.org/#!/documentation/concepts/ORM/Associations/OnetoMany.html)
- [Many-to-Many](http://sailsjs.org/#!/documentation/concepts/ORM/Associations/ManytoMany.html)

Can we try to come up with the formalized way to seed each of association by following convention already established in sails?

**Comment by givanse** [comment]
Ok, all we need is tests for that. I believe the PR already handles all of the associations. The current test is a many-to-many, therefore I assume the others are handled correctly, but more tests never hurt anybody.

**Comment by lykmapipo** [comment]
@givanse 

Good...I will review your codes and combine with what I have in mind so that we can a have a spec that we need to pass.

I appreciate your contribution.

**Comment by givanse** [comment]
Added more tests for the associations, also rebased.

**Comment by lykmapipo** [comment]
@givanse 

Am on it

**Pull request merged**
